# Generated by Django 4.2.5 on 2023-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["name"], name="account_use_name_a82ece_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="account_use_email_553b8f_idx"),
        ),
    ]
